Game.destroy_all
Game.create(name: "NBA 2K20", platform: "Playstation 4", genre: "Sports", rating: "E for Everyone", game_description: "NBA 2K20 is a platform for gamers and ballers to come together and create what’s next in basketball culture.", stock: 10)
Game.create(name: "NBA 2K20", platform: "Xbox One", genre: "Sports", rating: "E for Everyone", game_description: "NBA 2K20 is a platform for gamers and ballers to come together and create what’s next in basketball culture.", stock: 10 )
Game.create(name: "Mortal Kombat 11", platform: "Playstation 4", genre: "Fighting", rating: "M for Mature", game_description: "The new graphics engine showcasing every skull shattering, eye popping moment, brings you so close to the fight you can feel it.", stock: 10)
Game.create(name: "Mortal Kombat 11", platform: "Xbox One", genre: "Fighting", rating: "M for Mature", game_description: "The new graphics engine showcasing every skull shattering, eye popping moment, brings you so close to the fight you can feel it.", stock: 10)
Game.create(name: "Borderlands 3", platform: "Playstation 4", genre: "Shooter-Looter", rating: "M for Mature", game_description: "A mayhem fueled thrill ride: Stop the fanatical Calypso twins from uniting the bandit clans and claiming the galaxy’s ultimate power", stock: 10 )
Game.create(name: "Borderlands 3", platform: "Xbox One", genre: "Shooter-Looter", rating: "M for Mature", game_description: "A mayhem fueled thrill ride: Stop the fanatical Calypso twins from uniting the bandit clans and claiming the galaxy’s ultimate power", stock: 10 )
Game.create(name: "Mario Kart 8 Deluxe", platform: "Nintendo Switch", genre: "Racing", rating: "E for Everyone", game_description: "Hit the road with the definitive version of Mario Kart 8 and play anytime, anywhere!", stock: 10 )
Game.create(name: "Super Smash Bros. Ultimate", platform: "Nintendo Switch", genre: "Fighting", rating: "E for Everyone", game_description: "New stages and fighters are joined by the combined rosters of every past Super Smash Bros. game!", stock: 10 )
Game.create(name: "Minecraft", platform: "Nintendo Switch", genre: "Sandbox", rating: "E for Everyone", game_description: "Minecraft is a game about placing blocks and going on adventures", stock: 10 )
Game.create(name: "Animal Crossing: New Horizons", platform: "Nintendo Switch", genre: "Life Simulation", rating: "E for Everyone", game_description: "Build your community from scratch on a deserted island brimming with possibility!", stock: 0 )
Game.create(name: "Tom Clancy's Ghost Recon Breakpoint", platform: "Playstation 4", genre: "Tactical Shooter", rating: "M for Mature", game_description: "Put yourself in the shoes of a Spec Ops soldier stranded behind enemy lines as you explore the massive open world.", stock: 10 )
Game.create(name: "Tom Clancy's Ghost Recon Breakpoint", platform: "Xbox One", genre: "Tactical Shooter", rating: "M for Mature", game_description: "Put yourself in the shoes of a Spec Ops soldier stranded behind enemy lines as you explore the massive open world.", stock: 10 )
Game.create(name: "Grand Theft Auto V", platform: "Playstation 4", genre: "Action-Adventure", rating: "M for Mature", game_description: "The biggest, most dynamic and most diverse open world ever created and now packed with layers of new detail.", stock: 10)
Game.create(name: "Grand Theft Auto V", platform: "Xbox One", genre: "Action-Adventure", rating: "M for Mature", game_description: "The biggest, most dynamic and most diverse open world ever created and now packed with layers of new detail.", stock: 10)
Game.create(name: "Evil Within 2", platform: "Playstation 4", genre: "Survival Horror", rating: "M for Mature", game_description: "Return to the nightmare and win back your and your daughter", stock: 10)
Game.create(name: "Evil Within 2", platform: "Xbox One", genre: "Survival Horror", rating: "M for Mature", game_description: "Return to the nightmare and win back your and your daughter", stock: 10)
Game.create(name: "Madden NFL 20", platform: "Playstation 4", genre: "Sports", rating: "E for Everyone", game_description: "Be the Face of an NFL franchise where the decisions you make matter in your journey to become an NFL Superstar", stock: 10)
Game.create(name: "Madden NFL 20", platform: "Xbox One", genre: "Sports", rating: "E for Everyone", game_description: "Be the Face of an NFL franchise where the decisions you make matter in your journey to become an NFL Superstar", stock: 10)
Game.create(name: "Ghost of Tsushima", platform: "Playstation 4", genre: "Action-Adventure", rating: "M for Mature", game_description: "In this open-world action adventure, you'll roam vast countrysides and expansive terrain to encounter rich characters, discover ancient landmarks, and uncover the hidden beauty of Tsushima", stock: 10)
Game.create(name: "Persona 5 Royal", platform: "Playstation 4", genre: "JRPG", rating: "M for Mature", game_description: "Prepare for an all-new RPG experience in Persona 5 Royal, based in the universe of the award-wiining series, Persona!", stock: 10)
Game.create(name: "Marvel's Spiderman", platform: "Playstation 4", genre: "Action-Adventure", rating: "T for Teen", game_description: "The ultimate Spider-Man experience, available exclusively on Playsation!", stock: 10)
Game.create(name: "Forza Horizon 4", platform: "Xbox One", genre: "Racing", rating: "E for Everyone", game_description: "For the first time in the racing and driving genre, experience dynamic seasons in a shared open-world.", stock: 10)
Game.create(name: "Gears of War 5", platform: "Xbox One", genre: "First-person Shooter", rating: "M for Mature", game_description: "From one of the most acclaimed game franchises in history, Gears 5 delivers an epic campaing and brutal action across five thrilling modes.", stock: 10)
Game.create(name: "Halo: The Master Chief Collection", platform: "Xbox One", genre: "First-person Shooter", rating: "M for Mature", game_description: "For the first time ever, The Master Chief's entire story is on one console.", stock: 10)
Game.create(name: "Borderlands Legendary Collection", platform: "Nintendo Switch", genre: "Shooter-Looter", rating: "M for Mature", game_description: "Enjoy the first three games in the Borderland series with local two-player split-screen or four-player online play!", stock: 10)
Game.create(name: "Paper Mario: The Origami King", platform: "Nintendo Switch", genre: "Puzzle", rating: "E for Everyone", game_description: "A new paer-crafter Mario adventure unfolds on Nintendo Switch!", stock: 10)
Game.create(name: "Pokemon Sword", platform: "Nintendo Switch", genre: "JRPG", rating: "E for Everyone", game_description: "Experience a brand new Pokemon adventure as you explore the Galar Region and discover its secrets!", stock: 10)
Game.create(name: "Pokemon Shield", platform: "Nintendo Switch", genre: "JRPG", rating: "E for Everyone", game_description: "Experience a brand new Pokemon adventure as you explore the Galar Region and discover its secrets!", stock: 10)
Game.create(name: "Catherine: Full Body", platform: "Nintendo Switch", genre: "Puzzle", rating: "M for Mature", game_description: "Relieve this classic game as it has been remastered for the modern era! Play as Vincent and try to survive another night!", stock: 10)
Game.create(name: "Xenoblade Chronicles 2", platform: "Nintendo Switch", genre: "JRPG", rating: "T for Teen", game_description: "Join Rex as he travels the land to uncover the truth and save the world!", stock: 10)



User.destroy_all
User.create(name: "Andy", password: "game is life", age: 15)
User.create(name: "Allen", password: "game is life", age: 18)
User.create(name: "Ben", password: "game is life", age: 12)
User.create(name: "Lucy", password: "game is life", age: 22)
User.create(name: "Angel", password: "game is life", age: 20)
User.create(name: "Tom", password: "game is life", age: 28)
User.create(name: "Ryan", password: "game is life", age: 33)
User.create(name: "Evan", password: "game is life", age: 26)
User.create(name: "Judy", password: "game is life", age: 16)
User.create(name: "Jessica", password: "game is life", age: 24)

Checkout.destroy_all
Checkout.create(user_id:7, game_id:5, rating:8, comment:"feels good to keep shooting", checkout_date: 2020-12-19, return_date: 2020-04-26)
Checkout.create(user_id:9, game_id:7, rating:8, comment:"so much fun to play with family.", checkout_date: 2019-12-22, return_date: 2020-01-11)
Checkout.create(user_id:3, game_id:8, rating:7, comment:"fight was intense.", checkout_date: 2020-01-05, return_date: 2020-03-13)
Checkout.create(user_id:5, game_id:9, rating:6, comment:"freedom is mine", checkout_date: 2020-02-04, return_date: 2020-05-19)
Checkout.create(user_id:2, game_id:4, rating:4, comment:"it is cool", checkout_date: 2020-02-11, return_date: 2020-03-16)
Checkout.create(user_id:2, game_id:1, rating:8, comment:"ball is life", checkout_date: 2020-03-16, return_date: 2020-05-01)
Checkout.create(user_id:1, game_id:2, rating:8, comment:"player looks so real", checkout_date: 2020-05-20, return_date: 2020-07-22)
